[db.vector]
uri = "http://localhost"
db = ""

[db.app]
uri = "http://localhost"
db = ""

[cvs]
integration =  "github"
uri = ""
api_key = ""
days_to_look_back = 30

[llm.contextualizer]
model_name = "codeqwen:latest"
api_key = ""
temperature = 1.0
uri = "http://localhost:11434"

[llm.code_analyzer]
model_name = "codeqwen:latest"
api_key = ""
temperature = 0.3

[llm.doc_analyzer]
model_name = ""
api_key = ""
temperature = 1.0