name: Document Tool CI
on:
  push:
    paths:
      - libs/document_tool/**

jobs:
  document-tool-ci:
    name: Document Tool CI
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./libs/document_tool
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          version: "0.5.5"

      - name: Set up Python
        run: uv python install

      - name: Install the project
        run: uv sync --all-extras --dev

      - name: Run tests
        run: uv run pytest