name: State Manager CI
on:
  push:
    paths:
      - libs/state_manager/**

jobs:
  state-manager-lib-ci:
    name: State Manager lib CI
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./libs/state_manager
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          version: "0.5.5"

      - name: Set up Python
        run: uv python install

      - name: Install the project
        run: uv sync --all-extras --dev

      - name: Run tests
        run: uv run pytest